name: build-publish

on: [push]
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: build and copy slide
        run: |
          yarn build
          cp -r contents/slide public/
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: public

  publish:
    needs: [build]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build
          path: public
      - uses: chrislennon/action-aws-cli@v1.1
      - name: upload to s3
        run: |
          ls -al public
          aws s3 cp --recursive --only-show-errors public/ s3://aluc-io-v3/${{ github.sha }}/
          aws s3 rm --recursive --only-show-errors s3://aluc-io-v3/aluc.io/
          aws s3 cp --recursive --only-show-errors s3://aluc-io-v3/${{ github.sha }}/ s3://aluc-io-v3/aluc.io/
